"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.refineCommand = exports.coverageCommand = exports.checkCommand = exports.runCommand = exports.tasksCommand = exports.planCommand = exports.specifyCommand = exports.aiCommand = exports.templateCommand = exports.snapshotCommand = exports.traceCommand = exports.diffCommand = exports.genCommand = exports.validateCommand = exports.initCommand = void 0;
var init_1 = require("./init");
Object.defineProperty(exports, "initCommand", { enumerable: true, get: function () { return init_1.initCommand; } });
var validate_1 = require("./validate");
Object.defineProperty(exports, "validateCommand", { enumerable: true, get: function () { return validate_1.validateCommand; } });
var gen_1 = require("./gen");
Object.defineProperty(exports, "genCommand", { enumerable: true, get: function () { return gen_1.genCommand; } });
var diff_1 = require("./diff");
Object.defineProperty(exports, "diffCommand", { enumerable: true, get: function () { return diff_1.diffCommand; } });
var trace_1 = require("./trace");
Object.defineProperty(exports, "traceCommand", { enumerable: true, get: function () { return trace_1.traceCommand; } });
var snapshot_1 = require("./snapshot");
Object.defineProperty(exports, "snapshotCommand", { enumerable: true, get: function () { return snapshot_1.snapshotCommand; } });
var template_1 = require("./template");
Object.defineProperty(exports, "templateCommand", { enumerable: true, get: function () { return template_1.templateCommand; } });
var ai_1 = require("./ai");
Object.defineProperty(exports, "aiCommand", { enumerable: true, get: function () { return ai_1.aiCommand; } });
var specify_1 = require("./specify");
Object.defineProperty(exports, "specifyCommand", { enumerable: true, get: function () { return specify_1.specifyCommand; } });
var plan_1 = require("./plan");
Object.defineProperty(exports, "planCommand", { enumerable: true, get: function () { return plan_1.planCommand; } });
var tasks_1 = require("./tasks");
Object.defineProperty(exports, "tasksCommand", { enumerable: true, get: function () { return tasks_1.tasksCommand; } });
var run_1 = require("./run");
Object.defineProperty(exports, "runCommand", { enumerable: true, get: function () { return run_1.runCommand; } });
var check_1 = require("./check");
Object.defineProperty(exports, "checkCommand", { enumerable: true, get: function () { return check_1.checkCommand; } });
var coverage_1 = require("./coverage");
Object.defineProperty(exports, "coverageCommand", { enumerable: true, get: function () { return coverage_1.coverageCommand; } });
var refine_1 = require("./refine");
Object.defineProperty(exports, "refineCommand", { enumerable: true, get: function () { return refine_1.refineCommand; } });
